seed: 32
max_iters: 100
num_samples: 10     # number of samples to generate in each iteration
batch_size: 10       # batch size should be equal to num_samples for online training
step_per_epoch: 30   # number of policy updates in each iteration
warmup_size: 10
buffer_size: 10      # buffer size should be equal to num_samples for online training
load_checkpoint: true
checkpoint_every_n_iters: 10
optimizer: 
  lr: 5e-6
  cls: AdamW
  weight_decay: 0.01
loss:
  type: "grpo"
  clip_grpo_low: 0.2
  clip_grpo_high: 0.28
temperature_scheduler:
  _target_: gqe_qsci.gqe.scheduler.VarBasedScheduler
  initial: 0.5
  delta: 0.02
  target_var: 1e-5